import React from 'react'
import { Link } from 'react-router-dom'
import Digital from 'react-activity/lib/Digital';
import 'react-activity/lib/Digital/Digital.css';
import { Row, Col, Button, FormGroup, FormControl, Checkbox } from 'react-bootstrap'
import TransactionTokenProduct from './neighborhoods/Transaction Token Product'
import BusinessHeader from './neighborhoods/blocks/Business Header'

export default class BuyerTransactionWindow extends React.Component {

    state = {
        isLoading: false,
        details: [],
        next_view: false,
        token_error: false
    }



    async submitToken(){

        this.setState({ isLoading: true })

        var token = document.getElementById("token").value

                    const auth = localStorage.getItem('auth_code')

                    var formData = new FormData()
                    formData.append('token', token)


                    try {
                      const res = await fetch('https://www.iwansell.com/api/join_transaction/', {

                       body :formData,
                       method: 'POST',
                       credentials: 'same-origin',
                       mode: 'cors',

                       headers : {
                            'Authorization' : 'Token ' + auth,

                        },

                      });
                      const details = await res.json();
                      this.setState({
                        details
                      });

                    } catch (e) {
                      console.log(e);
                    }

                    this.setState({ isLoading: false})
                    this.evaluate_response()


    }



    evaluate_response(){

        if(this.state.details.seller){
            this.setState({ next_view: true})
        }else{
            this.setState({ token_error: true })
        }

    }





  render(){

    function FieldGroup({ id, label, help, ...props }) {
        return (
          <FormGroup controlId={id}>
            <div>{label}</div>
            <FormControl {...props} />
            {help && <div>{help}</div>}
          </FormGroup>
      );
    }


      return (
        <section className="buyer-transaction-window">
        <Row>
        <Col lg={4} lgOffset={4} md={4} mdOffset={4} sm={12} xs={12}>
            <BusinessHeader seller={false}/>
            <p className="transaction-header">Buyer Transaction Window</p>

            {this.state.isLoading ? (
                <div>
                    <p className="seller-product">Confirming token</p>
                <Row>
                <Col lg={3} lgOffset={5} md={3} mdOffset={5} sm={3} smOffset={5} xs={3} xsOffset={5}>
                    <Digital color="#ffffff" size={32}/>
                  </Col>
                </Row>
                </div>
            ) : (

            <div>
            {this.state.next_view ? (
                <TransactionTokenProduct
                transaction_id = {this.state.details.transaction_id}
                seller = {this.state.details.seller}
                token = {this.state.details.token}
                product_name = {this.state.details.product_name}
                product_image = {this.state.details.product_image}
                agreed_price = {this.state.details.agreed_price}
                payment_method = {this.state.details.payment_method}
                quantity = {this.state.details.quantity}/>

            ) : (
            <form>
                <Row>

               <Col lg={6} lgOffset={3} md={6} mdOffset={3} sm={6} smOffset={3} xs={6} xsOffset={3}>
                <FieldGroup
                  id="token"
                  label="Enter Token"
                  name="token"
                  placeholder=""
                />
                <p>This token is generated by the seller</p>

                {this.state.token_error ? (
                    <div><br /><p>{this.state.details.error_message}</p></div>
                ) : (
                    <div/>
                )}
                </Col>
                </Row>

                <Row>
                <Col lg={3} lgOffset={3} md={3} mdOffset={3} sm={4} smOffset={2} xs={4} xsOffset={2}>
                    <br /><Button bsStyle="success" onClick={this.submitToken.bind(this)}>Proceed</Button>
                </Col>

                 <Col lg={3} md={3} sm={6} xs={6}>
                 <Link to="/home">
                    <br /><Button bsStyle="danger">Cancel</Button>
                 </Link>
                </Col>
                </Row>
            </form>

            )}
            </div>


            )}


        </Col>
        </Row>
        </section>
      )
  }

}
